version: "3.9"

services:

  app:
    build:
      context: .
    image: apps_shop
    ports:
      - "80:8000"
    volumes:
      - ./apps:/apps
    command: python3 manage.py runserver 0.0.0.0:8000
